spring.application.name=zero-down
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/zero_down
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=e21aea1e61750009a4f1ccab6b5c4f4c075984e1635cd54e86c474d1355562b09d51c6c5

